# Compose schema version
version: '3.3'

# Overriding requirements
services:
  client:
    build:
      args:
        REQUIREMENTS: examples/coughvid/requirements.txt
    deploy:
      replicas: 5
    volumes:
      - ${HOST_DATA_DIR:-./examples/coughvid/data}:/var/data
      - /var/run/docker.sock:/var/run/docker.sock
